version: '3.8'
services:
  db: 
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db

    # Uncomment to change startup options
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    #  MONGO_INITDB_DATABASE: your-database-here

    ports:
      - 27017:27017

volumes:
  mongodb-data: